security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: secret
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: '{cipher}AgBMPCcJZhJkyay1MCFSxuBQAD6vc6EcFnKob4K2D8cYdsjRCUjONIZl9IktKHyLnqkvH5k+QdZELSLvcmuy4EZulwVaWCFZofU/G7mtTe5GJRM2MZjRB7u0NLLXajC6JAIHMcVptMyw1YboS0t8Wj3ULcYU6KcfCBY0A3B/RZSs6STXH7+vSEbBBrnWCxdO5mqC9Uj1IYAGTiSss2v/FvVzf2FubqGMXNM45zdPFmuOq7AuhBubJUprKYLsKmK6ulag8DzALbITdvH6qeMWUzXMFNCo5bagwYzuufcggES35JqPfCztCzM88wQCMsMqrj3Q++IVY9WrVwIZCxIKo3KoXGTC0CA2debEJrtVjdktjbLoG0nwCBc1c1LOVcYgygeF+SsPzZnHE+bZrt9uykWa1/ICgJh4WebdyEYS+HngfjvdslJtOqrl6FcqT72l4BXmiphJNEESSDG63tLkBXdqbC/HwUpaD9BArTxyJ0r/zf00x9XBY9IIaFWsxCQHYZP8/Nz7M+8xZ+x/sffSH4JImkEGYCwOOruj8vQJRCXZtkFq52Kw4iroXKR79fwt6IpcpmLGa6xWEpFYVxY/uy69PJfX9vLFyE/sBzkNdFPh1NDtxHQsixTEAl1xjEi5eYVBRe24BGAEehzamC09zNOdMhblrY/pDk0kXv4gE3L4qPSBIinT2Pt3HptGYDMn0gZamWkpFYThUdGANe700UGR'
      database: gribovodmicroserviceapp
      port: 27017

server:
  context-path: /accounts
  port: 5001

