spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: '{cipher}AgC3nARNt3kdy5VVAQkiMS+DU8Xfa1u+D2hpIHCzLRbExz1aFYmzQfe7z+LEzKzz1nxo/Uorni9ltUa8UdiayMGUvxRSs/rycySVys9bZt67CZZgjv+Oh72WHxmhg/istQVvHusnH9/tEC8lAfdONngBTkuc6M0n7vbKYONqGzH08YcSDV+aBZ5/5QNK29Jp9PvUuKQ6xNddAlgpfkULbjW44D+Os0U/vlVTM3gYkOCGpnRQZdGXIOvhZfPpMpo3wTQa4gSQaGnG5aCeWEWducs/DDo9GD9137drukkr1D8FJpgu+E43AxVDQWYjG1Xa5+nn1H14xrbXP58JBRTecEuPvbxTsI+FP+/FH/+N7FpUHFZINqF2Q8vcAs9yaUfWG6lwrE/labKwDDqsInw6DmqDAx8giMwsCJvJkbuYCFbW+6/amXhUMWH3yjpY5iqt4ecY5vsF37i+2XFOz2q9YPcP72j6Y84CjVpPgndBJu4yVUUhyWOariGBgNBx/znd5yYsZlA4ezhA4o3jjlsvuLeOBkMzA8Qv6+zW/eC5Qnr9ZFE/+naruZ5RRf03lE0jyDQZnrUbjod7yw1lIiaUbNQRz+J3sGwZq2kHO19w8uaSjqz97lOt00Gjxtmd7orOhjSP17AUluzz4TX5tGfSrfR5dHKM6X9RrE2gLsiamDAlTiXGgJwIDEI32d8iMCux66b8DP9wPsZrPSqDnnHGfwDG'
      database: gribovodmicroserviceapp
      port: 27017

server:
  context-path: /auth
  port: 5000

security:
  oauth2:
    resource:
    filter-order : 3

jwt:
  key-store:
    path: jwt.jks
    alias: 'jwt-key'
    password: '{cipher}AgBBWVXQMjT8MjiuoTQ0ssbW4d6Ijhw8D/E7ehB/ymoctADHYt4g0jEGkP10AZWEmWQJhL9y2D8Bnz6DJBepwtiucGcBKAAtRUwUN5B43v0phMwhQBytI4YD/6dCgov9ibPWMN9zR7MQO11bWYYWdKIVcx7kEjiPKxOLA8fLm6QY2/KQkyFUqweOtPVsoe3VRwwtS1c0bP3EdOWjng7LT9D2RYz5meqyGS7/zDlZeV7koOUffyuQhBNJHNdQlDcYVd5SVOs/CAqBsltdq/wUXf8kc6tzj7+zcqVKeQ26zLhcc0VL3qrGlfSsS+OFXTkRaaguI1aF8TXzcJa6VpFVoIIUecfWJjIzyRwks7TJ3GDGnTw7RwdGPqx5eFRLkTK31Zo90flYcelEWYKO9K0oT4I+5Z+534GVL7hGC5AVok0cxX2EqZbYt9C2lUPEgqCWcxs3P3+bOJDw8zI2sfRh7QI6WAH+cFZo3mO3b3ylkbxvWghknBVTjmWchTK0l5F/NYgxdwytSJyZKg1yyBufY5OU4FnWDOu2de70uLTlsWD4w1ikPopVR+YBkzEaOE+g4sFstC6p8lcWcps7/C35YGoR7o0+d1fKl2xQp3Zb18yrYPMgGmJRYgNpX9pc0y/enOPQ1HP9Y/d7nJLUaIciQXQrCHeWSgNVZQOKqBT5KdjTAbVooqXG8CeRso2rehgQT9eonJc9KJBo9Q8PbsqhpHc2'